Variables controlled for Cerebrovascular diseases (I60-I69) Deaths:

Year 
Year & Month
Ten Year Age Groups
Sex
Single Race 6
Education
2013 Urbanization
State


```{r}
library(here)
library(ggplot2)
library(readr)
library(dplyr)
options(scipen=999) #normale Zahlen statt 2e+05 oder so
```

Year
```{r}
file_path <- here("Datasets", "Univariate Analysis", "Cerebrovascular Diseases", "Year", "Cerebro_by_Year.csv")
year_df <- read_csv(file_path, show_col_types = FALSE)
year_df

ggplot(year_df %>% filter(!is.na(Year)), aes(x = Year, y = Deaths)) +
  geom_line(color = "red", size = 1) +
  geom_point(color = "red", size = 2) +
  labs(title = "Cerebrovascular Diseases Deaths per Year",
       x = "Year",
       y = "Number of Deaths") +
  theme_minimal()

# Plot 2: Deaths Normalized by Population (Crude Rate)
ggplot(year_df %>% filter(!is.na(Year)), aes(x = Year, y = (Deaths / Population) * 100000)) +
  geom_line(color = "blue", size = 1) +
  geom_point(color = "blue", size = 2) +
  labs(title = "Cerebrovascular Diseases Death Rate per 100,000 Population",
       x = "Year",
       y = "Death Rate per 100,000") +
  theme_minimal()

year_df %>%
  filter(!is.na(Year)) %>%
  ggplot(aes(x = Year, y = `Age Adjusted Rate`, fill = Year)) +
  geom_bar(stat = "identity") +
  labs(title = "Cerebrovascular Diseases Death Rate by Year, Age adjusted (per 100,000 Population)",
       x = "Year",
       y = "Death Rate per 100,000") +
  theme_minimal()
```


Year & Month
```{r}
file_path <- here("Datasets", "Univariate Analysis", "Cerebrovascular Diseases", "Year & Month", "Cerebro_by_Year&Month.csv")
ym_df <- read_csv(file_path, show_col_types = FALSE)
ym_df
ym_df %>%
  filter(!is.na(Month)) %>%
  mutate(Month_Only = substr(Month, 1, 3), 
         Month_Only = factor(Month_Only, levels = month.abb)) %>%
  group_by(Month_Only) %>%
  summarise(Deaths = sum(Deaths, na.rm = TRUE)) %>%
  ggplot(aes(x = Month_Only, y = Deaths, fill = Month_Only)) +
  geom_bar(stat = "identity") +
  labs(title = "Cerebrovascular Diseases Deaths per Month (Jan-Dec)",
       x = "Month",
       y = "Number of Deaths") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none")

ym_df %>%
  filter(!is.na(Month)) %>%
  mutate(Month_Only = substr(Month, 1, 3),  
         Month_Only = factor(Month_Only, levels = month.abb)) %>%  
  group_by(Month_Only) %>%
  summarise(Deaths = sum(Deaths, na.rm = TRUE)) %>%  
  ungroup() %>%  
  mutate(mean_Deaths = mean(Deaths, na.rm = TRUE)) %>%  
  ggplot(aes(x = Month_Only, y = Deaths, fill = Month_Only)) +
  geom_bar(stat = "identity") +
  geom_hline(aes(yintercept = mean_Deaths), linetype = "dashed", color = "red", size = 1) +  
  labs(title = "Cerebrovascular Diseases Deaths per Month (Jan-Dec)",
       x = "Month",
       y = "Number of Deaths") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none")

ym_df %>%
  filter(!is.na(Month)) %>%
  mutate(Month = factor(Month, levels = unique(Month), ordered = TRUE)) %>%
  ggplot(aes(x = Month, y = Deaths, group = 1)) +
  geom_line(color = "red", size = 1) +
  geom_point(color = "red", size = 2) +
  geom_smooth() +
  labs(title = "Cerebrovascular Diseases Deaths per Month (Jan 2018 - Dec 2023)",
       x = "Month",
       y = "Number of Deaths") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_discrete(breaks = ym_df$Month[seq(1, 80, by = 2)])  # Show every 2th month
```

10 Year Age Groups
```{r}
file_path <- here("Datasets", "Univariate Analysis", "Cerebrovascular Diseases", "Ten Year Age Groups", "Cerebro_by_AgeGroup10.csv")
age_df <- read_csv(file_path, show_col_types = FALSE)
age_df$Population <- as.numeric(age_df$Population)
age_df
age_groups_order <- c(
  "< 1 year",
  "1-4 years",
  "5-14 years",
  "15-24 years",
  "25-34 years",
  "35-44 years",
  "45-54 years",
  "55-64 years",
  "65-74 years",
  "75-84 years",
  "85+ years"
)

age_df %>%
  filter(!is.na(`Ten-Year Age Groups`)) %>%
    filter(`Ten-Year Age Groups` != "Not Stated") %>%
    mutate(`Ten-Year Age Groups` = factor(`Ten-Year Age Groups`, levels = age_groups_order)) %>%
  ggplot(aes(x = `Ten-Year Age Groups`, y = Deaths, fill = `Ten-Year Age Groups`)) +
  geom_bar(stat = "identity") +
  labs(title = "Cerebrovascular Diseases Deaths by Age Group",
       x = "Age Group",
       y = "Number of Deaths") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Plot 2: Deaths by Sex Normalized with Population (Bar Plot)
age_df %>%
  filter(!is.na(`Ten-Year Age Groups`)) %>%
  filter(`Ten-Year Age Groups` != "Not Stated") %>%
    mutate(`Ten-Year Age Groups` = factor(`Ten-Year Age Groups`, levels = age_groups_order)) %>%
  ggplot(aes(x = `Ten-Year Age Groups`, y = (Deaths / Population) * 100000, fill = `Ten-Year Age Groups`)) +
  geom_bar(stat = "identity") +
  labs(title = "Cerebrovascular Diseases Death Rate by Age Group (per 100,000 Population)",
       x = "Age Group",
       y = "Death Rate per 100,000") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
Sex
```{r}
file_path <- here("Datasets", "Univariate Analysis", "Cerebrovascular Diseases", "Sex", "Cerebro_by_Sex.csv")
sex_df <- read_csv(file_path, show_col_types = FALSE)
sex_df$age_adjusted_rate <- c(129.3, 201.6, 166.0, 166.0)
sex_df

sex_df %>%
  filter(!is.na(Sex)) %>%
  ggplot(aes(x = Sex, y = Deaths, fill = Sex)) +
  geom_bar(stat = "identity") +
  labs(title = "Cerebrovascular Diseases Deaths by Sex",
       x = "Sex",
       y = "Number of Deaths") +
  theme_minimal()

# Plot 2: Deaths by Sex Normalized with Population (Bar Plot)
sex_df %>%
  filter(!is.na(Sex)) %>%
  ggplot(aes(x = Sex, y = (Deaths / Population) * 100000, fill = Sex)) +
  geom_bar(stat = "identity") +
  labs(title = "Cerebrovascular Diseases Death Rate by Sex (per 100,000 Population)",
       x = "Sex",
       y = "Death Rate per 100,000") +
  theme_minimal()

sex_df %>%
  filter(!is.na(Sex)) %>%
  ggplot(aes(x = Sex, y = age_adjusted_rate, fill = Sex)) +
  geom_bar(stat = "identity") +
  labs(title = "Cerebrovascular Diseases Death Rate by Sex, Age adjusted (per 100,000 Population)",
       x = "Sex",
       y = "Death Rate per 100,000") +
  theme_minimal()
```


Race
```{r}
file_path <- here("Datasets", "Univariate Analysis", "Cerebrovascular Diseases", "Race", "Cerebro_by_Race.csv")
race_df <- read_csv(file_path, show_col_types = FALSE)
race_df$age_adjusted_rate <- c(109.1, 82.6, 210.9, 148.1, 166.0, 69.8, 166.0, 166.0)
race_df


race_df %>%
  filter(!is.na(`Single Race 6`)) %>%
  ggplot(aes(x = `Single Race 6`, y = Deaths)) +
  geom_bar(stat = "identity") +
  labs(title = "Cerebrovascular Diseases Deaths by Race",
       x = "Race",
       y = "Number of Deaths") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Plot 2: Deaths by Race Normalized with Population (Bar Plot)
race_df %>%
  filter(!is.na(`Single Race 6`)) %>%
  ggplot(aes(x = `Single Race 6`, y = (Deaths / Population) * 100000)) +
  geom_bar(stat = "identity") +
  labs(title = "Cerebrovascular Diseases Death Rate by Race (per 100,000 Population)",
       x = "Race",
       y = "Death Rate per 100,000") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

race_df %>%
  filter(!is.na(`Single Race 6`)) %>%
  ggplot(aes(x = `Single Race 6`, y = age_adjusted_rate)) +
  geom_bar(stat = "identity") +
  labs(title = "Cerebrovascular Diseases Death Rate by Race Age adjusted (per 100,000 Population)",
       x = "Race",
       y = "Death Rate per 100,000") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


Education
```{r}
file_path <- here("Datasets", "Univariate Analysis", "Cerebrovascular Diseases", "Education", "Cerebro_by_Education.csv")
education_df <- read_csv(file_path, show_col_types = FALSE)
education_df

#Education Attainment for 25 or older: https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_educational_attainment
#Nich Bachelor oder mehr /Percentage - Bachelor or Higher/Percentage
sum(education_df$Deaths[1:3])/0.484 - sum(education_df$Deaths[4:8])/0.516



education_order <- c(
  "8th grade or less",
  "9th through 12th grade with no diploma",
  "High school graduate or GED completed",
  "Some college credit, but not a degree.",
  "Associate degree (AA,AS)",
  "Bachelor?s degree (BA, AB, BS)",
  "Master?s degree (MA, MS, MEng, MEd, MSW, MBA)",
  "Doctorate (PhD, EdD) or Professional Degree (MD, DDS, DVM, LLB, JD)",
  "Unknown or Not Stated"
)

education_df %>%
  filter(!is.na(Education)) %>%
  filter(Education != "Not Available") %>%
  mutate(Education = factor(Education, levels = education_order)) %>%
  ggplot(aes(x = Education, y = Deaths, fill = Education)) +
  geom_bar(stat = "identity") +
  labs(title = "Cerebrovascular Diseases Deaths by Education Attainment Level",
       x = "Education Attainment Level",
       y = "Number of Deaths") +
  theme_minimal() +
  theme(axis.text.x = element_blank())


education_df %>%
  filter(!is.na(Education)) %>%
  filter(Education != "Not Available") %>%
  mutate(Education = factor(Education, levels = education_order)) %>%
  ggplot(aes(x = "", y = Deaths, fill = Education)) +  
  geom_bar(stat = "identity", width = 1) +  
  coord_polar(theta = "y") +  
  labs(title = "Cerebrovascular Diseases Deaths by Education Attainment Level") +
  theme_minimal() +
  theme(axis.text.x = element_blank(),  
        axis.text.y = element_blank(),  
        axis.ticks = element_blank(),   
        panel.grid = element_blank(),
        axis.title = element_blank()) 
```


Urbanization
```{r}
file_path <- here("Datasets", "Univariate Analysis", "Cerebrovascular Diseases", "Urbanization", "Cerebro_by_Urbanization.csv")
urban_df <- read_csv(file_path, show_col_types = FALSE)
urban_df
# Percentage of people living in each Urbanization level (https://www.cdc.gov/nchs/data/series/sr_02/sr02_166.pdf)
urbanization_data <- data.frame(
  Urbanization_Level = c("Large central metro", "Large fringe metro", "Medium metro", 
                         "Small metro", "Micropolitan", "Noncore"),
  Number_of_Counties = c(68, 368, 373, 358, 641, 1335),
  Population_Percent = c(30.5, 24.7, 20.9, 9.2, 8.7, 6.1)
)
urbanization_data$Deaths <- urban_df$Deaths[1:6]
urbanization_data$Deaths_per_Pop <- urbanization_data$Deaths / urbanization_data$Population_Percent #if all levels had the same amout of people there
urbanization_data$Urbanization_Level <- factor(urbanization_data$Urbanization_Level, 
                                               levels = c("Large central metro", "Large fringe metro", 
                                                          "Medium metro", "Small metro", "Micropolitan", "Noncore"))
urbanization_data


urbanization_data %>%
  filter(!is.na(Urbanization_Level)) %>%
  ggplot(aes(x = Urbanization_Level, y = Deaths, fill = Urbanization_Level)) +
  geom_bar(stat = "identity") +
  labs(title = "Cerebrovascular Diseases Deaths by Urbanization",
       x = "Urbanization levels",
       y = "Number of Deaths") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

urbanization_data %>%
  ggplot(aes(x = Urbanization_Level, y = Population_Percent, fill = Urbanization_Level)) +
  geom_bar(stat = "identity") +
  labs(title = "Percenatage of Population in Urbanization Levels",
       x = "Urbanization levels",
       y = "Percentage") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

urbanization_data %>%
  ggplot(aes(x = Urbanization_Level, y = Deaths_per_Pop, fill = Urbanization_Level)) +
  geom_bar(stat = "identity") +
  labs(title = "Cerebrovascular Diseases Deaths by Urbanization Level, normalized",
       x = "Urbanization levels",
       y = "Normalized Number of Deaths") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


State
```{r}
file_path <- here("Datasets", "Univariate Analysis", "Cerebrovascular Diseases", "State", "Cerebro_by_State.csv")
state_df <- read_csv(file_path, show_col_types = FALSE)
state_df

republican_states <- c("Alabama", "Alaska", "Arkansas", "Florida", "Idaho", 
                       "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", 
                       "Mississippi", "Missouri", "Montana", "Nebraska", 
                       "North Carolina", "North Dakota", "Ohio", "Oklahoma", 
                       "South Carolina", "South Dakota", "Tennessee", "Texas", 
                       "Utah", "West Virginia", "Wyoming")

state_df <- state_df %>%
  mutate(Party = ifelse(State %in% republican_states, "Republican", "Democratic"))

avg_death_rates <- state_df %>%
  group_by(Party) %>%
  summarize(Average_Death_Rate = mean((Deaths / Population) * 100000, na.rm = TRUE))

state_df %>%
  filter(!is.na(State)) %>%
  ggplot(aes(x = State, y = Deaths, fill = Party)) +
  geom_bar(stat = "identity") +
  labs(title = "Cerebrovascular Diseases Deaths by State",
       x = "State",
       y = "Number of Deaths") +
  theme_minimal() +
  scale_fill_manual(values = c("Republican" = "red", "Democratic" = "blue")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

state_df %>%
  filter(!is.na(State)) %>%
  ggplot(aes(x = State, y = (Deaths / Population) * 100000, fill = Party)) +
  geom_bar(stat = "identity") +
  labs(title = "Cerebrovascular Diseases Death Rate by State (per 100,000 Population)",
       x = "State",
       y = "Death Rate per 100,000") +
  theme_minimal() +
  scale_fill_manual(values = c("Republican" = "red", "Democratic" = "blue")) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
state_df %>%
  filter(!is.na(State)) %>%
  ggplot(aes(x = State, y = (Deaths / Population) * 100000, fill = Party)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("Republican" = "red", "Democratic" = "blue")) +
  geom_hline(data = avg_death_rates, aes(yintercept = Average_Death_Rate, color = Party), linetype = "solid", size = 1) +
  scale_color_manual(values = c("Republican" = "darkred", "Democratic" = "darkblue")) +
  labs(title = "Cerebrovascular Diseases Death Rate by State (per 100,000 Population)",
       x = "State",
       y = "Death Rate per 100,000",
       fill = "Party",
       color = "Average Death Rate") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

state_df %>%
  filter(!is.na(State)) %>%
  ggplot(aes(x = State, y = `Age Adjusted Rate`, fill = Party)) +
  geom_bar(stat = "identity") +
  labs(title = "Cerebrovascular Diseases Death Rate by State Age adjusted (per 100,000 Population)",
       x = "State",
       y = "Death Rate per 100,000") +
  theme_minimal() +
  scale_fill_manual(values = c("Republican" = "red", "Democratic" = "blue")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```